version: '3.1'
services:
    redis:
        image: redis
        ports:
            - '6379:6379'
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=root
            - HTTP_PASSWORD=123456
        ports:
            - '8081:8081'
        depends_on:
            - redis
# Acredito que vou ter que especificar a rede quando estiver usando o zscaler
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
